swagger: "2.0"
info:
  title: API Моего склада
  description: API упралвения складом
  version: 1.0.0
host: api.sklad.stepanenko.dev
tags:
  - name: "Товары"
schemes:
  - http
paths:
  /goods:
    post:
      tags:
        - "Товары"
      summary: Добавление товара
      description: Добавляет товар на склад
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Good"
      responses:
        200:
          description: OK
        400:
          description: Некорректный запрос
definitions:
  Good:
    type: "object"
    properties:
      article:
        type: "string"
      name:
        type: "string"
      lastBuyPrice:
        type: integer
        minimum: 0
      lastSellPrice:
        type: integer
        minimum: 0
    required:
      - article
      - name
      - lastBuyPrice
